pilyoung() ::=<<
<span id='myname'>PILYOUNG KIM</span>
<p>
Post-doctoral Research Fellow<br>
<a href="http://www.nimh.nih.gov/index.shtml">National Institute of<br> Mental Health (NIMH)</a>
<p>
<a href="http://neuroscience.nih.gov/Lab.asp?Org_ID=457">Section on Bipolar Spectrum Disorders<br>
Emotion and Development Branch</a>
<p>
pilyoung.kim at nih.gov
<p>
Building 15K -MSC 2670<br>
Bethesda, MD 20892-2670<br>
<p>
(301) 594-1378
>>